dist: trusty
language: cpp
compiler:
 - gcc
 - clang
addons:
  apt:
    #sources:
      #- sourceline 'ppa:beineri/opt-qt542-trusty'
    packages:
      - qt5-default
install:
 - git submodule update --init --recursive
 - mkdir build && cd build
script: cmake --build . --target all

